service: instagram-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-south-1
  stage: dev
  environment:
    DYNAMODB_TABLE_NAME: instagram-cache
    SCRAPER_API_KEY: ${ssm:/instagram-api/dev/SCRAPER_API_KEY}
    SCRAPINGDOG_API_KEY: ${ssm:/instagram-api/dev/SCRAPINGDOG_API_KEY}
    SENTRY_DSN: ${ssm:/instagram-api/dev/SENTRY_DSN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:ap-south-1:*:table/instagram-cache"
        - Effect: Allow
          Action:
            - ssm:GetParameters
            - ssm:GetParameter
          Resource: "arn:aws:ssm:ap-south-1:*:parameter/instagram-api/dev/*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  api:
    handler: handler.scrape
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: /api/scrape
          method: post
          cors: true
