service: instagram-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-south-1
  stage: dev
  environment:
    # सीधे .env फ़ाइल से वेरिएबल्स लोड करें
    SCRAPER_API_KEY: ${env:SCRAPER_API_KEY}
    SCRAPINGDOG_API_KEY: ${env:SCRAPINGDOG_API_KEY}
    DYNAMODB_TABLE_NAME: instagram-cache
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:ap-south-1:*:table/instagram-cache"

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin  # .env फ़ाइल सपोर्ट के लिए

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    noDeploy:
      - boto3
      - botocore
      - s3transfer
      - urllib3
    useDownloadCache: true
    useStaticCache: true

functions:
  api:
    handler: handler.scrape
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: /api/scrape
          method: post
          cors: true